In [1]:
#Pandas - Loading the data to the python program
!pip install pandas #installing pandas in our notebook 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#matplotlib - Data Visulization from the python Grapjs,Plots
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
#Scikit-learn - Preprocessing, evalusting, Ml Algoritm loading 
!pip install Scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [5]:
#Seaborn is a library that uses Matplotlib underneath to plot graphs. It will be used to visualize random distributions.
!pip install seaborn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [8]:
import pandas as pd
dataset=pd.read_csv('spam.csv',encoding="latin-1")
dataset

class                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [16]:
df = pd.read_csv('spam.csv',encoding="latin-1")
df


class                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [19]:
#visualizing dataset
df.head(n=10)

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [20]:
df.shape

(5572, 5)

In [21]:
#to check whether target attribute is binary or not
np.unique(df['class'])

array(['ham', 'spam'], dtype=object)

In [22]:
np.unique(df['message'])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [23]:
x=df["message"].values
y=df["class"].values

#create count vectorizer object
cv=CountVectorizer()

x=cv.fit_transform(x)
v=x.toarray()

print(v)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:

first_col=df.pop('message')
df.insert(0,'message',first_col)
df


message class Unnamed: 2  \
0     Go until jurong point, crazy.. Available only ...   ham        NaN   
1                         Ok lar... Joking wif u oni...   ham        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam        NaN   
3     U dun say so early hor... U c already then say...   ham        NaN   
4     Nah I don't think he goes to usf, he lives aro...   ham        NaN   
...                                                 ...   ...        ...   
5567  This is the 2nd time we have tried 2 contact u...  spam        NaN   
5568              Will Ì_ b going to esplanade fr home?   ham        NaN   
5569  Pity, * was in mood for that. So...any other s...   ham        NaN   
5570  The guy did some bitching but I acted like i'd...   ham        NaN   
5571                         Rofl. Its true to its name   ham        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [25]:

train_x=x[:4180]
train_y=y[:4180]

test_x=x[4180:]
test_y=y[4180:]

In [26]:

bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(train_x,train_y)

y_pred_train=bnb.predict(train_x)
y_pred_test=bnb.predict(test_x)


In [27]:
#training score
print(bnb.score(train_x,train_y)*100)

#testing score
print(bnb.score(test_x,test_y)*100)


98.70813397129187
98.20402298850574


In [28]:

from sklearn.metrics import classification_report
print(classification_report(train_y,y_pred_train))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3615
        spam       0.99      0.91      0.95       565

    accuracy                           0.99      4180
   macro avg       0.99      0.95      0.97      4180
weighted avg       0.99      0.99      0.99      4180



In [29]:

from sklearn.metrics import classification_report
print(classification_report(test_y,y_pred_test))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1210
        spam       0.99      0.87      0.93       182

    accuracy                           0.98      1392
   macro avg       0.99      0.93      0.96      1392
weighted avg       0.98      0.98      0.98      1392

